// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChcJFr5nkxXTruz03YC4oO4ieRK_hIzUw',
    appId: '1:244014039102:web:c5c2c173afb7126d52116f',
    messagingSenderId: '244014039102',
    projectId: 'gymahmed-cd701',
    authDomain: 'gymahmed-cd701.firebaseapp.com',
    databaseURL: 'https://gymahmed-cd701-default-rtdb.firebaseio.com',
    storageBucket: 'gymahmed-cd701.appspot.com',
    measurementId: 'G-BGWS8MTFWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvli7t_UGgB2iBAc1LUejWxsq84izItoM',
    appId: '1:244014039102:android:f31d6198a0c2afa652116f',
    messagingSenderId: '244014039102',
    projectId: 'gymahmed-cd701',
    databaseURL: 'https://gymahmed-cd701-default-rtdb.firebaseio.com',
    storageBucket: 'gymahmed-cd701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0nX9ZeCjMWJR_CQgdKN29tvCnMC5tSaA',
    appId: '1:244014039102:ios:9f45072fb7b80fb652116f',
    messagingSenderId: '244014039102',
    projectId: 'gymahmed-cd701',
    databaseURL: 'https://gymahmed-cd701-default-rtdb.firebaseio.com',
    storageBucket: 'gymahmed-cd701.appspot.com',
    iosBundleId: 'com.example.luby2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0nX9ZeCjMWJR_CQgdKN29tvCnMC5tSaA',
    appId: '1:244014039102:ios:9f45072fb7b80fb652116f',
    messagingSenderId: '244014039102',
    projectId: 'gymahmed-cd701',
    databaseURL: 'https://gymahmed-cd701-default-rtdb.firebaseio.com',
    storageBucket: 'gymahmed-cd701.appspot.com',
    iosBundleId: 'com.example.luby2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChcJFr5nkxXTruz03YC4oO4ieRK_hIzUw',
    appId: '1:244014039102:web:c5c2c173afb7126d52116f',
    messagingSenderId: '244014039102',
    projectId: 'gymahmed-cd701',
    authDomain: 'gymahmed-cd701.firebaseapp.com',
    databaseURL: 'https://gymahmed-cd701-default-rtdb.firebaseio.com',
    storageBucket: 'gymahmed-cd701.appspot.com',
    measurementId: 'G-BGWS8MTFWR',
  );

}